CREATE TABLE IF NOT EXISTS PENDENCIA (
                ID_PENDENCIA_FINANCEIRA SERIAL NOT NULL,
                CPF						 VARCHAR(11),
                DOCUMENTO				 VARCHAR(20),
                VALOR_ORIGINAL			 NUMBER(15,2),
                DT_PENDENCIA			 TIMESTAMP,
                CNPJCPF_ORIGEM_PENDENCIA VARCHAR(14),
                CODIGO_CLIENTE			 INTEGER,
                DT_CADASTRO              TIMESTAMP,
CONSTRAINT PENDENCIA_PKEY PRIMARY KEY (ID_PENDENCIA_FINANCEIRA));                

CREATE INDEX IDX_PENDENCIA_01 ON PENDENCIA (CPF);

CREATE INDEX IDX_PENDENCIA_02 ON PENDENCIA (CPF, DOCUMENTO);